/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author bole
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNumberText = new javax.swing.JTextField();
        secondNumberText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plusButtton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        mnoziButton = new javax.swing.JButton();
        devideButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kakulator");

        jLabel1.setText("prvi broj");

        jLabel2.setText("drugi broj");

        plusButtton.setText("+");
        plusButtton.setToolTipText("add");
        plusButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButttonActionPerformed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.setToolTipText("subtract");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        answerLabel.setText("Resenje je:");

        mnoziButton.setText("*");
        mnoziButton.setToolTipText("mnozi");
        mnoziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnoziButtonActionPerformed(evt);
            }
        });

        devideButton.setText("/");
        devideButton.setToolTipText("devide");
        devideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devideButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Shruti", 1, 18)); // NOI18N
        jLabel3.setText("Vrlo, vrlo jednostavan kalkulator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(firstNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(plusButtton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(minusButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(mnoziButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(devideButton))
                                        .addComponent(secondNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButtton)
                    .addComponent(minusButton)
                    .addComponent(mnoziButton)
                    .addComponent(devideButton))
                .addGap(39, 39, 39)
                .addComponent(answerLabel)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButttonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los prvi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            number2 = Double.parseDouble(
                    this.secondNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los drugi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 + number2;
        this.answerLabel.setText("The answer is: "
                + answer);

    }//GEN-LAST:event_plusButttonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los prvi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            number2 = Double.parseDouble(
                    this.secondNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los drugi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 - number2;
        this.answerLabel.setText("The answer is: "
                + answer);

    }//GEN-LAST:event_minusButtonActionPerformed

    private void mnoziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnoziButtonActionPerformed
       double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los prvi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            number2 = Double.parseDouble(
                    this.secondNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los drugi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 * number2;
        this.answerLabel.setText("The answer is: "
                + answer); 
        
    }//GEN-LAST:event_mnoziButtonActionPerformed

    private void devideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devideButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los prvi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            number2 = Double.parseDouble(
                    this.secondNumberText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los drugi broj",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 / number2;
        this.answerLabel.setText("The answer is: "
                + answer);
    }//GEN-LAST:event_devideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton devideButton;
    private javax.swing.JTextField firstNumberText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton mnoziButton;
    private javax.swing.JButton plusButtton;
    private javax.swing.JTextField secondNumberText;
    // End of variables declaration//GEN-END:variables
}
